// ignore_for_file: prefer_collection_literals

class Autogenerated {
  int? code;
  bool? status;
  String? message;
  String? data;
  List<String>? pagination;

  Autogenerated(
      {this.code, this.status, this.message, this.data, this.pagination});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    status = json['status'];
    message = json['message'];
    data = json['data'];
    if (json['pagination'] != null) {
      pagination = <String>[];
      json['pagination'].forEach((v) {
        pagination!.add(v.toString());
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data['code'] = code;
    data['status'] = status;
    data['message'] = message;
    data['data'] = this.data;
    if (pagination != null) {
      data['pagination'] = pagination!.toList();
    }
    return data;
  }
}
