class ModelRedeiveLeadDeal {
  int? code;
  bool? status;
  String? message;
  List<RedeiveLeadDealData>? data;

  ModelRedeiveLeadDeal({this.code, this.status, this.message, this.data});

  ModelRedeiveLeadDeal.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    status = json['status'];
    message = json['message'];
    if (json['data'] != null) {
      data = <RedeiveLeadDealData>[];
      json['data'].forEach((v) {
        data!.add(new RedeiveLeadDealData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class RedeiveLeadDealData {
  int? id;
  String? dealName;
  String? inviteQrCode;
  String? documentUrl;
  String? commissionTransType;
  String? inviteLink;

  RedeiveLeadDealData(
      {this.id,
      this.dealName,
      this.inviteQrCode,
      this.documentUrl,
      this.commissionTransType,
      this.inviteLink});

  RedeiveLeadDealData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    dealName = json['deal_name'];
    inviteQrCode = json['invite_qr_code'];
    documentUrl = json['document_url'];
    commissionTransType = json['commission_trans_type'];
    inviteLink = json['invite_link'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['deal_name'] = this.dealName;
    data['invite_qr_code'] = this.inviteQrCode;
    data['document_url'] = this.documentUrl;
    data['commission_trans_type'] = this.commissionTransType;
    data['invite_link'] = this.inviteLink;
    return data;
  }
}
class Autogenerated {
  int? code;
  bool? status;
  String? message;
  List<Data>? data;

  Autogenerated({this.code, this.status, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    code = json['code'];
    status = json['status'];
    message = json['message'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(new Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['code'] = this.code;
    data['status'] = this.status;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int? id;
  String? dealName;
  String? inviteQrCode;
  String? documentUrl;
  String? commissionTransType;
  String? inviteLink;

  Data(
      {this.id,
      this.dealName,
      this.inviteQrCode,
      this.documentUrl,
      this.commissionTransType,
      this.inviteLink});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    dealName = json['deal_name'];
    inviteQrCode = json['invite_qr_code'];
    documentUrl = json['document_url'];
    commissionTransType = json['commission_trans_type'];
    inviteLink = json['invite_link'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['deal_name'] = this.dealName;
    data['invite_qr_code'] = this.inviteQrCode;
    data['document_url'] = this.documentUrl;
    data['commission_trans_type'] = this.commissionTransType;
    data['invite_link'] = this.inviteLink;
    return data;
  }
}

